export {default as Home} from './Home/index'
export {default as Register} from './Register/Register'
export {default as Login } from './Login/Login'
export {default as Profile} from './Profile/Profile'
export {default as Operation} from './Operations/Operations'
export {default as Reports} from './Reports/Reports'
export {default as Notifications} from './Notifications/Notifications'
export {default as Messages} from './Messages/Messages'
export {default as NewOperation} from './NewOperation/NewOperation'