export {default as Home} from './Home/index'
export {default as Register} from './Register/Register'
export {default as Login } from './Login/Login'
export {default as Profile} from './Profile/Profile'
export {default as Operation} from './Operations/Operations'
export {default as ActiveReports} from './ActiveReports/ActiveReports'
export {default as ClosedReports} from './ClosedReports/ClosedReports'
export {default as Notifications} from './Notifications/Notifications'
export {default as Messages} from './Messages/Messages'
export {default as NewOperation} from './NewOperation/NewOperation'
export {default as EmailActivation} from './EmailActivation/EmailActivation'
export {default as ResetPassword} from './ResetPassword/ResetPassword'
export {default as Tickets} from './Tickets/Tickets'
export {default as Ticket} from './Ticket/Ticket'