export {default as Header} from './Header/Header'
export {default as Footer} from './Footer/Footer' 
export {default as Carousel} from './Carousel/Carousel'
export {default as Loader} from './Loader/Loader'
export {default as About } from './About/About' 
export {default as Contact} from './Contact/Contact'
export {default as SideNavbar} from './SideNavbar/SideNavbar'
export {default as NotificationContainer} from './NotifyContainer/NotifyContainer'
export {default as Input} from './Input/Input'
export {default as SideButton} from './sideButton/SideButton'
export {default as Button} from './Button/Button'
export {default as Address} from './Address/Address'
export {default as Personal} from './Personal/Personal'
export {default as Documents} from './Document/Document'
export {default as Phones} from './Phone/Phone'
export {default as Credential} from './Credential/Credential'
export {default as Done} from './DoneRegister/DoneRegister'
export {default as Progress} from './Progress/Progress'
